name: build-irislite
on:
  workflow_dispatch:
  push:
    paths:
      - '**.c'
      - '**.m'
      - '**.h'
      - 'Makefile'
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          sudo xcode-select -s /Applications/Xcode.app || true
          make
          file IrisLite.dylib
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: IrisLite-dylib
          path: IrisLite.dylib
